separator=true
separator_block_width=48
markup=pango
command=~/.local/bin/dotfiles/i3blocks/$BLOCK_NAME

[net]
color=#7aa2f7
interval=10

[disk]
color=#9ece6a
interval=60

[memory]
color=#9ece6a
interval=5

[cpu]
color=#9ece6a
interval=2

[battery]
color=#78a083
interval=15

[volume]
color=#bb9af7
interval=2

[datetime]
color=#e6e6e6
interval=30
