separator=true
separator_block_width=48
markup=pango
command=~/.local/bin/dotfiles/i3blocks/$BLOCK_NAME

[net]
color=#3b82f6
interval=10

[disk]
color={color2}
interval=60

[memory]
color={color2}
interval=5

[cpu]
color={color2}
interval=2

[battery]
color={color2}
interval=2

[volume]
color=#a855f7
interval=2

[datetime]
color=#d4d4d4
interval=30
