foreground #f4f7fb
background #101214
selection_foreground #101214
selection_background {color9}
cursor {color9}
color0 #101214
color1 {color9}
color2 {color10}
color3 {color11}
color4 {color12}
color5 {color13}
color6 {color14}
color7 #f4f7fb
color8 #6f7880
color9 {color9}
color10 {color10}
color11 {color11}
color12 {color12}
color13 {color13}
color14 {color14}
color15 #ffffff
