backend = "glx";
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;

corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow = true;
shadow-radius = 18;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.26;
shadow-exclude = [
  "name = 'Notification'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;
fade-delta = 4;

animations = false;
animation-stiffness = 320;
animation-dampening = 28;
animation-window-mass = 0.45;
animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-for-transient-window = "slide-down";

blur-method = "dual_kawase";
blur-strength = 5;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

opacity-rule = [
  "94:class_g = 'kitty'",
  "96:class_g = 'Rofi'",
  "94:class_g = 'dunst'"
];

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.95; focus = true; full-shadow = false; };
  dock = { shadow = false; };
  dnd = { shadow = false; };
};
